SELECT 'DATA PROFILING: SILVER OIL' AS category;
SUMMARIZE silver_oil;

SELECT 'DATA PROFILING: SILVER COAL' AS category;
SUMMARIZE silver_coal;

SELECT 'DATA PROFILING: SILVER CEMENT' AS category;
SUMMARIZE silver_cement;
