name: ELT Pipeline

on:
  workflow_dispatch:
    inputs:
      target:
        description: "coal / cement / oil / all"
        required: false
        default: "all"

jobs:

  ingestion:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:

        - dataset: coal
          lambda: ingestion-coal
          script: ingestion_coal.py
          handler: ingestion_coal.lambda_handler
          prefix: bronze/energy/coal
          api_key: FRED_API_KEY

        - dataset: cement
          lambda: ingestion-cement
          script: ingestion_cement.py
          handler: ingestion_cement.lambda_handler
          prefix: bronze/construction/cement
          api_key: FRED_API_KEY

        - dataset: oil
          lambda: ingestion-oil
          script: ingestion_oil.py
          handler: ingestion_oil.lambda_handler
          prefix: bronze/energy/brent
          api_key: EIA_API_KEY
          
          if: github.event.inputs.target == 'all' || github.event.inputs.target == matrix.dataset

    permissions:
      id-token: write
      contents: read

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Package Lambda
        run: |
          mkdir package
          pip install requests==2.31.0 -t package/
          cp src/bronze/${{ matrix.script }} package/
          cd package && zip -r ../lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Lambda code
        run: |
          aws lambda update-function-code \
            --function-name ${{ matrix.lambda }} \
            --zip-file fileb://lambda.zip --no-cli-pager

      - name: Wait for Lambda update
        run: |
         aws lambda wait function-updated \
         --function-name ${{ matrix.lambda }}

      - name: Update Lambda config
        run: |
          aws lambda update-function-configuration \
            --function-name ${{ matrix.lambda }} \
            --handler ${{ matrix.handler }} \
            --runtime python3.12 \
            --timeout 300 \
            --memory-size 256 \
            --environment "Variables={${{ matrix.api_key }}=${{ secrets[matrix.api_key] }},S3_BUCKET=${{ secrets.S3_BUCKET }},S3_PREFIX=${{ matrix.prefix }}}" \
            --no-cli-pager

      - name: Invoke Lambda
        run: |
          aws lambda invoke \
            --function-name ${{ matrix.lambda }} \
            --payload '{}' response.json
          cat response.json


  bronze-transform:

    needs: ingestion
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install DuckDB CLI
        run: |

          wget https://github.com/duckdb/duckdb/releases/latest/download/duckdb_cli-linux-amd64.zip
          # Cek apakah filenya beneran ada (buat debug)
          ls -l
          unzip duckdb_cli-linux-amd64.zip
          chmod +x ./duckdb


      - name: Run Transform & Profile
        env:
          motherduck_token: ${{ secrets.MD_TOKEN }}
        run: |
          # 1. Profiling Data
          for file in src/silver/profiling_data/*.sql; do
            ./duckdb md:my_db < "$file"
          done
          
          # 2. Jalankan Transformasi
          for file in src/silver/ddl/*.sql; do
            ./duckdb md:my_db < "$file"
          done
          
          # 3. Generate Report ke Markdown dari file
          ./duckdb md:my_db -markdown < src/silver/final_check_quality.sql > PROFILE_REPORT.md
          for file in src/silver/final_check_quality.sql; do
            ./duckdb md:my_db < "$file"
          done


      - name: Run Logic Bussiness
        env:
          motherduck_token: ${{ secrets.MD_TOKEN }}
        run: |
          # 1. Unified Data
          for file in src/gold/unified.sql; do
            ./duckdb md:my_db < "$file"
          done

          # 2. Indexed 
          for file in src/gold/indexed.sql; do
            ./duckdb md:my_db < "$file"
          done

          # 3. Gap Cost & Profit
          for file in src/gold/gap.sql; do
            ./duckdb md:my_db < "$file"
          done

          # 4. Lag Effect
          for file in src/gold/lag.sql; do
            ./duckdb md:my_db < "$file"
          done

