name: ELT Pipeline

on:
  workflow_dispatch:

jobs:
  elt:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1 - checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2 - setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Step 3 - install deps and package Lambda
      - name: Install Python dependencies
        run: |
          mkdir package
          python -m pip install --upgrade pip
          pip install -r src/pipeline/requirements.txt -t package/
          cp -r src/pipeline/* package/
          cd package
          zip -r ../deployment_package.zip . 

      # Step 4 - configure AWS 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ${{ secrets.get.AWS_REGION }}

      # Step 5 - verify credentials
      - name: Verify AWS credentials
        run: aws sts get-caller-identity

      # Step 6 - update Lambda
      - name: Update Lambda Code
        run: |
          aws lambda update-function-code \
            --function-name lambda_ingest \
            --zip-file fileb://deployment_package.zip

      # Step 9 — load data to MotherDuck
      - name: Load to MotherDuck
        env:
          MD_TOKEN: ${{ secrets.MD_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          MD_RAW_TABLE: "raw_events"
        run: python src/pipeline/load_to_motherduck.py

      # Step 10 — SQL transforms
      - name: Run transformations in MotherDuck
        env:
          MD_TOKEN: ${{ secrets.MD_TOKEN }}
        run: python src/pipeline/transform.py
        
     # Step 11 — basic validation
      - name: Run data validation
        env:
          MD_TOKEN: ${{ secrets.MD_TOKEN }}
        run: python src/pipeline/validate.py

     # Step 12 - export to s3 
      - name: Export Results to S3
        env:
          MD_TOKEN: ${{ secrets.MD_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: python src/pipeline/export_to_s3.py
